### ISSUE TITLE
Implement `real_world` front end part

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/real_world#1]
React would be the best option: https://play.kotlinlang.org/hands-on/Building%20Web%20Applications%20with%20React%20and%20Kotlin%20JS/01_Introduction

**Comment by jaguililla** [comment]
Hi @donky106 would you like to continue working on this task? If you can't give it time... I understand :) just let me know (in order to move it to the backlog or work on it)... Thanks!

**Comment by donky106** [comment]
Hi Juanjo,

Sorry for late answer, your email landed in the spam box. I am not sure this issue was a good choice for me, I am not a front end developer. Sorry 😔. Please move it to the backlog.

Sorry for wasting your time.

Best,
Yulia
-------- Original Message --------

**Comment by jaguililla** [comment]
No worries, it is not a waste of time... Thanks for your contributions :)

**Comment by jaguililla** [comment]
Won't be done unless a Front End module is developed
